name: Build

on:
  push:
    branches: [ dev, master, deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Node installation
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Code checkout
      uses: actions/checkout@v2

    - name: Dependencies install
      run: npm ci

    - name: Build
      run: npm run build-prod

    - name: Build upload
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Build download
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Upload to hotbox
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --endpoint-url https://hb.bizmrg.com --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: delivery-borscht
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: "build"
